/**
 * MacroMedica — Rich Mock Data
 * Covers all workflow stages so the dashboard shows realistic data
 * when no live Supabase data is available.
 *
 * Visit workflow: waiting → called → consultation → billing → completed
 * RDV workflow:   confirme (scheduled) → appears in PreviewCard
 */

const TODAY = new Date().toISOString().slice(0, 10)
const TZ_OFFSET = '+01:00'

function dt(hour, min = 0) {
  return `${TODAY}T${String(hour).padStart(2, '0')}:${String(min).padStart(2, '0')}:00${TZ_OFFSET}`
}

// ── Doctors ─────────────────────────────────────────────────────────────────
export const MOCK_DOCTORS = [
  {
    id: 'doc_001',
    nom_complet: 'Dr. Othmane Touggani',
    first_name: 'Othmane',
    last_name: 'Touggani',
    role: 'doctor',
    status: 'active',
    cabinet_id: 'cab_demo',
    specialite: 'Médecine générale',
  },
  {
    id: 'doc_002',
    nom_complet: 'Dr. Sanae Lahlou',
    first_name: 'Sanae',
    last_name: 'Lahlou',
    role: 'doctor',
    status: 'active',
    cabinet_id: 'cab_demo',
    specialite: 'Pédiatrie',
  },
]

// ── Patients ─────────────────────────────────────────────────────────────────
export const MOCK_PATIENTS = [
  { id: 'pat_01', nom: 'Benali', prenom: 'Ahmed', telephone: '+212 661 82 11 54', date_naissance: '1987-06-14', sexe: 'homme', groupe_sanguin: 'O+', allergies: 'Pénicilline', mutuelle: 'CNOPS', ville: 'Casablanca', cabinet_id: 'cab_demo' },
  { id: 'pat_02', nom: 'Chraibi', prenom: 'Fatima', telephone: '+212 623 45 67 81', date_naissance: '1992-03-09', sexe: 'femme', groupe_sanguin: 'A+', allergies: 'Aucune', mutuelle: 'CNSS', ville: 'Rabat', cabinet_id: 'cab_demo' },
  { id: 'pat_03', nom: 'Idrissi', prenom: 'Youssef', telephone: '+212 634 56 78 12', date_naissance: '1979-11-22', sexe: 'homme', groupe_sanguin: 'B+', allergies: 'Pollen', mutuelle: 'Assurance', ville: 'Rabat', cabinet_id: 'cab_demo' },
  { id: 'pat_04', nom: 'Alaoui', prenom: 'Salma', telephone: '+212 645 67 81 23', date_naissance: '2001-01-17', sexe: 'femme', groupe_sanguin: 'AB+', allergies: 'Aucune', mutuelle: 'Aucune', ville: 'Marrakech', cabinet_id: 'cab_demo' },
  { id: 'pat_05', nom: 'Tazi', prenom: 'Meryem', telephone: '+212 656 78 12 34', date_naissance: '1984-08-30', sexe: 'femme', groupe_sanguin: 'A-', allergies: 'Iode', mutuelle: 'CNOPS', ville: 'Fès', cabinet_id: 'cab_demo' },
  { id: 'pat_06', nom: 'Bennani', prenom: 'Omar', telephone: '+212 667 81 23 45', date_naissance: '1968-05-02', sexe: 'homme', groupe_sanguin: 'O-', allergies: 'Aspirine', mutuelle: 'CNSS', ville: 'Tanger', cabinet_id: 'cab_demo' },
  { id: 'pat_07', nom: 'Lahlou', prenom: 'Nadia', telephone: '+212 678 12 34 56', date_naissance: '1995-12-11', sexe: 'femme', groupe_sanguin: 'B-', allergies: 'Aucune', mutuelle: 'Mutuelle privée', ville: 'Casablanca', cabinet_id: 'cab_demo' },
  { id: 'pat_08', nom: 'Amrani', prenom: 'Karim', telephone: '+212 689 23 45 67', date_naissance: '1975-09-18', sexe: 'homme', groupe_sanguin: 'AB-', allergies: 'Latex', mutuelle: 'CNSS', ville: 'Meknès', cabinet_id: 'cab_demo' },
  { id: 'pat_09', nom: 'Boukili', prenom: 'Hind', telephone: '+212 690 34 56 78', date_naissance: '1989-04-04', sexe: 'femme', groupe_sanguin: 'A+', allergies: 'Aucune', mutuelle: 'CNOPS', ville: 'Agadir', cabinet_id: 'cab_demo' },
  { id: 'pat_10', nom: 'Kadiri', prenom: 'Soufiane', telephone: '+212 601 45 67 89', date_naissance: '1998-10-27', sexe: 'homme', groupe_sanguin: 'O+', allergies: 'Fruits de mer', mutuelle: 'Aucune', ville: 'Casablanca', cabinet_id: 'cab_demo' },
  { id: 'pat_11', nom: 'El Fassi', prenom: 'Zineb', telephone: '+212 612 34 56 78', date_naissance: '1972-07-15', sexe: 'femme', groupe_sanguin: 'A+', allergies: 'Sulfamides', mutuelle: 'CNOPS', ville: 'Fès', cabinet_id: 'cab_demo' },
  { id: 'pat_12', nom: 'Berrada', prenom: 'Hassan', telephone: '+212 623 45 12 34', date_naissance: '1960-03-20', sexe: 'homme', groupe_sanguin: 'B+', allergies: 'Aucune', mutuelle: 'CNSS', ville: 'Casablanca', cabinet_id: 'cab_demo' },
  { id: 'pat_13', nom: 'Mansouri', prenom: 'Lina', telephone: '+212 634 56 23 45', date_naissance: '2003-09-10', sexe: 'femme', groupe_sanguin: 'O+', allergies: 'Aucune', mutuelle: 'Mutuelle privée', ville: 'Rabat', cabinet_id: 'cab_demo' },
  { id: 'pat_14', nom: 'Cherkaoui', prenom: 'Mehdi', telephone: '+212 645 67 34 56', date_naissance: '1991-12-05', sexe: 'homme', groupe_sanguin: 'AB+', allergies: 'Pénicilline', mutuelle: 'CNSS', ville: 'Casablanca', cabinet_id: 'cab_demo' },
  { id: 'pat_15', nom: 'Kettani', prenom: 'Rania', telephone: '+212 656 78 45 67', date_naissance: '1985-06-28', sexe: 'femme', groupe_sanguin: 'A-', allergies: 'Aucune', mutuelle: 'CNOPS', ville: 'Marrakech', cabinet_id: 'cab_demo' },
]

// ── RDV (Today's Scheduled Appointments — appear in PreviewCard) ──────────────
export const MOCK_RDV = [
  {
    id: 'rdv_01',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_04',
    date_rdv: dt(9, 0),
    status: 'confirme',
    motif: 'Première consultation',
    notes: 'Nouvelle patiente, bilan général',
    created_at: dt(8, 0),
    updated_at: dt(8, 0),
    patients: { id: 'pat_04', nom: 'Alaoui', prenom: 'Salma', telephone: '+212 645 67 81 23' },
    doctor_id: 'doc_001',
  },
  {
    id: 'rdv_02',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_07',
    date_rdv: dt(10, 30),
    status: 'confirme',
    motif: 'Suivi diabète',
    notes: 'HbA1c à vérifier',
    created_at: dt(8, 0),
    updated_at: dt(8, 0),
    patients: { id: 'pat_07', nom: 'Lahlou', prenom: 'Nadia', telephone: '+212 678 12 34 56' },
    doctor_id: 'doc_001',
  },
  {
    id: 'rdv_03',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_11',
    date_rdv: dt(11, 15),
    status: 'confirme',
    motif: 'Renouvellement ordonnance',
    notes: 'Traitement anti-hypertenseur',
    created_at: dt(8, 0),
    updated_at: dt(8, 0),
    patients: { id: 'pat_11', nom: 'El Fassi', prenom: 'Zineb', telephone: '+212 612 34 56 78' },
    doctor_id: 'doc_002',
  },
  {
    id: 'rdv_04',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_13',
    date_rdv: dt(14, 0),
    status: 'confirme',
    motif: 'Consultation pédiatrique',
    notes: 'Contrôle de croissance 6 mois',
    created_at: dt(8, 0),
    updated_at: dt(8, 0),
    patients: { id: 'pat_13', nom: 'Mansouri', prenom: 'Lina', telephone: '+212 634 56 23 45' },
    doctor_id: 'doc_002',
  },
  {
    id: 'rdv_05',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_15',
    date_rdv: dt(15, 30),
    status: 'confirme',
    motif: 'Bilan annuel',
    notes: 'Bilan lipidique + NFS demandé',
    created_at: dt(8, 0),
    updated_at: dt(8, 0),
    patients: { id: 'pat_15', nom: 'Kettani', prenom: 'Rania', telephone: '+212 656 78 45 67' },
    doctor_id: 'doc_001',
  },
]

// ── Visits (Workflow queue — all stages represented) ─────────────────────────
export const MOCK_VISITS = [
  // 1. WAITING — arrived and queued
  {
    id: 'vis_01',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_01',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'waiting',
    queue_number: 1,
    queue_date: TODAY,
    motif: 'Contrôle tension artérielle',
    source: 'appointment',
    queued_at: dt(8, 10),
    queue_sort_at: dt(8, 10),
    created_at: dt(8, 10),
    updated_at: dt(8, 10),
    patients: { id: 'pat_01', nom: 'Benali', prenom: 'Ahmed', telephone: '+212 661 82 11 54', allergies: 'Pénicilline', mutuelle: 'CNOPS' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: { id: null, date_rdv: dt(8, 30), notes: 'Contrôle HTA' },
  },
  // 2. WAITING — second in queue
  {
    id: 'vis_02',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_02',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'waiting',
    queue_number: 2,
    queue_date: TODAY,
    motif: 'Suivi post-traitement',
    source: 'walk_in',
    queued_at: dt(8, 25),
    queue_sort_at: dt(8, 25),
    created_at: dt(8, 25),
    updated_at: dt(8, 25),
    patients: { id: 'pat_02', nom: 'Chraibi', prenom: 'Fatima', telephone: '+212 623 45 67 81', allergies: 'Aucune', mutuelle: 'CNSS' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: null,
  },
  // 3. CALLED — patient called to doctor's office
  {
    id: 'vis_03',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_03',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'called',
    queue_number: 3,
    queue_date: TODAY,
    motif: 'Suivi diabète type 2',
    source: 'appointment',
    queued_at: dt(8, 0),
    queue_sort_at: dt(8, 40),
    created_at: dt(8, 0),
    updated_at: dt(8, 40),
    patients: { id: 'pat_03', nom: 'Idrissi', prenom: 'Youssef', telephone: '+212 634 56 78 12', allergies: 'Pollen', mutuelle: 'Assurance' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: { id: null, date_rdv: dt(9, 0), notes: 'Analyse HbA1c' },
  },
  // 4. CONSULTATION — in the middle of consultation
  {
    id: 'vis_04',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_05',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'consultation',
    queue_number: 4,
    queue_date: TODAY,
    motif: 'Douleurs articulaires',
    source: 'appointment',
    queued_at: dt(7, 55),
    queue_sort_at: dt(8, 15),
    created_at: dt(7, 55),
    updated_at: dt(8, 15),
    patients: { id: 'pat_05', nom: 'Tazi', prenom: 'Meryem', telephone: '+212 656 78 12 34', allergies: 'Iode', mutuelle: 'CNOPS' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: { id: null, date_rdv: dt(8, 0), notes: 'Douleur genou droit' },
  },
  // 5. CONSULTATION — second doctor's patient in consultation
  {
    id: 'vis_05',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_12',
    doctor_id: 'doc_002',
    rdv_id: null,
    status: 'consultation',
    queue_number: 1,
    queue_date: TODAY,
    motif: 'Contrôle pédiatrique',
    source: 'appointment',
    queued_at: dt(8, 5),
    queue_sort_at: dt(8, 20),
    created_at: dt(8, 5),
    updated_at: dt(8, 20),
    patients: { id: 'pat_12', nom: 'Berrada', prenom: 'Hassan', telephone: '+212 623 45 12 34', allergies: 'Aucune', mutuelle: 'CNSS' },
    doctor: { id: 'doc_002', nom_complet: 'Dr. Sanae Lahlou', first_name: 'Sanae', last_name: 'Lahlou', role: 'doctor' },
    rdv: { id: null, date_rdv: dt(8, 30), notes: 'Vaccins à jour' },
  },
  // 6. BILLING — consultation done, waiting for payment
  {
    id: 'vis_06',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_06',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'billing',
    queue_number: 5,
    queue_date: TODAY,
    motif: 'Bilan annuel',
    billing_amount: 350,
    billing_type: 'cash',
    source: 'appointment',
    queued_at: dt(7, 30),
    queue_sort_at: dt(7, 50),
    created_at: dt(7, 30),
    updated_at: dt(8, 30),
    patients: { id: 'pat_06', nom: 'Bennani', prenom: 'Omar', telephone: '+212 667 81 23 45', allergies: 'Aspirine', mutuelle: 'CNSS' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: { id: null, date_rdv: dt(8, 0), notes: 'Résultats labo' },
  },
  // 7. BILLING — second billing patient
  {
    id: 'vis_07',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_14',
    doctor_id: 'doc_002',
    rdv_id: null,
    status: 'billing',
    queue_number: 2,
    queue_date: TODAY,
    motif: 'Consultation générale',
    billing_amount: 250,
    billing_type: 'insurance',
    source: 'walk_in',
    queued_at: dt(7, 45),
    queue_sort_at: dt(8, 0),
    created_at: dt(7, 45),
    updated_at: dt(8, 45),
    patients: { id: 'pat_14', nom: 'Cherkaoui', prenom: 'Mehdi', telephone: '+212 645 67 34 56', allergies: 'Pénicilline', mutuelle: 'CNSS' },
    doctor: { id: 'doc_002', nom_complet: 'Dr. Sanae Lahlou', first_name: 'Sanae', last_name: 'Lahlou', role: 'doctor' },
    rdv: null,
  },
  // 8. COMPLETED — consultation finished and paid
  {
    id: 'vis_08',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_08',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'completed',
    queue_number: 6,
    queue_date: TODAY,
    motif: 'Suivi cardiologie',
    billing_amount: 500,
    billing_type: 'cash',
    source: 'appointment',
    queued_at: dt(7, 0),
    queue_sort_at: dt(7, 20),
    created_at: dt(7, 0),
    updated_at: dt(7, 55),
    patients: { id: 'pat_08', nom: 'Amrani', prenom: 'Karim', telephone: '+212 689 23 45 67', allergies: 'Latex', mutuelle: 'CNSS' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: { id: null, date_rdv: dt(7, 30), notes: 'ECG normal' },
  },
  // 9. BILLING — Pending payment
  {
    id: 'vis_09',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_09',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'billing',
    queue_number: 7,
    queue_date: TODAY,
    motif: 'Consultation gynécologie & suivi',
    billing_amount: 300,
    billing_type: 'cash',
    source: 'appointment',
    queued_at: dt(8, 30),
    queue_sort_at: dt(8, 45),
    created_at: dt(8, 30),
    updated_at: dt(9, 15),
    patients: { id: 'pat_09', nom: 'Boukili', prenom: 'Hind', telephone: '+212 690 34 56 78', allergies: 'Aucune', mutuelle: 'CNOPS' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: null,
  },
  // 10. BILLING — Pending payment
  {
    id: 'vis_10',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_10',
    doctor_id: 'doc_002',
    rdv_id: null,
    status: 'billing',
    queue_number: 8,
    queue_date: TODAY,
    motif: 'Certificat médical de sport',
    billing_amount: 200,
    billing_type: 'card',
    source: 'walk_in',
    queued_at: dt(8, 40),
    queue_sort_at: dt(9, 0),
    created_at: dt(8, 40),
    updated_at: dt(9, 30),
    patients: { id: 'pat_10', nom: 'Kadiri', prenom: 'Soufiane', telephone: '+212 601 45 67 89', allergies: 'Fruits de mer', mutuelle: 'Aucune' },
    doctor: { id: 'doc_002', nom_complet: 'Dr. Sanae Lahlou', first_name: 'Sanae', last_name: 'Lahlou', role: 'doctor' },
    rdv: null,
  },
  // 11. BILLING — Pending payment
  {
    id: 'vis_11',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_11',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'billing',
    queue_number: 9,
    queue_date: TODAY,
    motif: 'Bilan de contrôle tensionnel',
    billing_amount: 300,
    billing_type: 'cash',
    source: 'appointment',
    queued_at: dt(9, 0),
    queue_sort_at: dt(9, 15),
    created_at: dt(9, 0),
    updated_at: dt(9, 45),
    patients: { id: 'pat_11', nom: 'El Fassi', prenom: 'Zineb', telephone: '+212 612 34 56 78', allergies: 'Sulfamides', mutuelle: 'CNOPS' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: null,
  },
  // 12. BILLING — Pending payment
  {
    id: 'vis_12',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_15',
    doctor_id: 'doc_002',
    rdv_id: null,
    status: 'billing',
    queue_number: 10,
    queue_date: TODAY,
    motif: 'Consultation dermatologie',
    billing_amount: 400,
    billing_type: 'transfer',
    source: 'appointment',
    queued_at: dt(9, 15),
    queue_sort_at: dt(9, 30),
    created_at: dt(9, 15),
    updated_at: dt(10, 0),
    patients: { id: 'pat_15', nom: 'Kettani', prenom: 'Rania', telephone: '+212 656 78 45 67', allergies: 'Aucune', mutuelle: 'CNOPS' },
    doctor: { id: 'doc_002', nom_complet: 'Dr. Sanae Lahlou', first_name: 'Sanae', last_name: 'Lahlou', role: 'doctor' },
    rdv: null,
  },
  // 13. COMPLETED — second completed patient
  {
    id: 'vis_09',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_09',
    doctor_id: 'doc_002',
    rdv_id: null,
    status: 'completed',
    queue_number: 3,
    queue_date: TODAY,
    motif: 'Certificat médical',
    billing_amount: 150,
    billing_type: 'cash',
    source: 'walk_in',
    queued_at: dt(7, 15),
    queue_sort_at: dt(7, 30),
    created_at: dt(7, 15),
    updated_at: dt(8, 0),
    patients: { id: 'pat_09', nom: 'Boukili', prenom: 'Hind', telephone: '+212 690 34 56 78', allergies: 'Aucune', mutuelle: 'CNOPS' },
    doctor: { id: 'doc_002', nom_complet: 'Dr. Sanae Lahlou', first_name: 'Sanae', last_name: 'Lahlou', role: 'doctor' },
    rdv: null,
  },
  // 10. WAITING — walk-in, no appointment
  {
    id: 'vis_10',
    clinic_id: 'cab_demo',
    cabinet_id: 'cab_demo',
    patient_id: 'pat_10',
    doctor_id: 'doc_001',
    rdv_id: null,
    status: 'waiting',
    queue_number: 7,
    queue_date: TODAY,
    motif: 'Maux de tête, fatigue',
    source: 'walk_in',
    queued_at: dt(9, 10),
    queue_sort_at: dt(9, 10),
    created_at: dt(9, 10),
    updated_at: dt(9, 10),
    patients: { id: 'pat_10', nom: 'Kadiri', prenom: 'Soufiane', telephone: '+212 601 45 67 89', allergies: 'Fruits de mer', mutuelle: 'Aucune' },
    doctor: { id: 'doc_001', nom_complet: 'Dr. Othmane Touggani', first_name: 'Othmane', last_name: 'Touggani', role: 'doctor' },
    rdv: null,
  },
]

// ── Consultations (past records) ─────────────────────────────────────────────
export const MOCK_CONSULTATIONS = [
  { id: 'con_01', cabinet_id: 'cab_demo', patient_id: 'pat_08', montant: 500, statut: 'paye', date_consult: TODAY, notes: 'Suivi post-stent. TA stable 12/8. Maintien bisoprolol.', created_at: dt(7, 55), patients: { nom: 'Amrani', prenom: 'Karim' } },
  { id: 'con_02', cabinet_id: 'cab_demo', patient_id: 'pat_09', montant: 150, statut: 'paye', date_consult: TODAY, notes: 'Certificat médical sport amateur. Examen clinique normal.', created_at: dt(8, 0), patients: { nom: 'Boukili', prenom: 'Hind' } },
  { id: 'con_03', cabinet_id: 'cab_demo', patient_id: 'pat_01', montant: 350, statut: 'paye', date_consult: new Date(Date.now() - 86400000).toISOString().slice(0, 10), notes: 'HTA légère. Amlodipine 5mg le soir. Contrôle dans 1 mois.', created_at: dt(10, 0), patients: { nom: 'Benali', prenom: 'Ahmed' } },
  { id: 'con_04', cabinet_id: 'cab_demo', patient_id: 'pat_03', montant: 400, statut: 'credit', date_consult: new Date(Date.now() - 86400000).toISOString().slice(0, 10), notes: 'Diabète T2 équilibré partiellement. HbA1c 7.2%. Poursuite Metformine.', created_at: dt(11, 0), patients: { nom: 'Idrissi', prenom: 'Youssef' } },
  { id: 'con_05', cabinet_id: 'cab_demo', patient_id: 'pat_06', montant: 0, statut: 'annule', date_consult: new Date(Date.now() - 2 * 86400000).toISOString().slice(0, 10), notes: 'RDV annulé par le patient.', created_at: dt(9, 0), patients: { nom: 'Bennani', prenom: 'Omar' } },
  { id: 'con_06', cabinet_id: 'cab_demo', patient_id: 'pat_05', montant: 300, statut: 'paye', date_consult: new Date(Date.now() - 3 * 86400000).toISOString().slice(0, 10), notes: 'Arthrose genou droit. Kinésithérapie recommandée.', created_at: dt(14, 0), patients: { nom: 'Tazi', prenom: 'Meryem' } },
  { id: 'con_07', cabinet_id: 'cab_demo', patient_id: 'pat_11', montant: 250, statut: 'paye', date_consult: new Date(Date.now() - 4 * 86400000).toISOString().slice(0, 10), notes: 'Renouvellement traitement HTA. Énalapril 10mg. Bilan rénal demandé.', created_at: dt(9, 30), patients: { nom: 'El Fassi', prenom: 'Zineb' } },
  { id: 'con_08', cabinet_id: 'cab_demo', patient_id: 'pat_02', montant: 200, statut: 'credit', date_consult: new Date(Date.now() - 5 * 86400000).toISOString().slice(0, 10), notes: 'Suivi post-opératoire gynécologique. Évolution favorable.', created_at: dt(15, 0), patients: { nom: 'Chraibi', prenom: 'Fatima' } },
]

// ── Stats for the dashboard header cards ─────────────────────────────────────
export const MOCK_STATS = {
  patientsToday: MOCK_VISITS.length,
  rdvToday: MOCK_RDV.length,
  revenueToday: MOCK_CONSULTATIONS
    .filter(c => c.date_consult === TODAY && c.statut === 'paye')
    .reduce((sum, c) => sum + (c.montant || 0), 0),
  waiting: MOCK_VISITS.filter(v => v.status === 'waiting').length,
  consultation: MOCK_VISITS.filter(v => v.status === 'consultation').length,
  billing: MOCK_VISITS.filter(v => v.status === 'billing').length,
  completed: MOCK_VISITS.filter(v => v.status === 'completed').length,
}
